---
all: 
  hosts: 
        localhost:
            ansible_host: 127.0.0.1  

  
  children:
    application:
      hosts:  
        app01:
          ansible_host: 192.168.1.1

        app02:
          ansible_host: 192.168.1.2
        
      vars: 
          ansible_port: 22 
          ansible_connection: ssh 
          ansible_user: sysadmin
          

    database:
      hosts:  
        dbmaster:
          ansible_host: 192.168.1.3

        dbslave:
          ansible_host: 192.168.1.4
        
      vars: 
          ansible_port: 22 
          ansible_connection: ssh 
          ansible_user: sysadmin