---

- name: Update Ubuntu OS
  hosts: all
  gather_facts: yes
  become: true

  tasks:

    - name: Update Debian Linux VMs
      block:
       
        - name: Update apt repo and cache
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        - name: Upgrade all apt packages
          apt: upgrade=dist force_apt_get=yes

      when: ( ansible_facts["os_family"] == "Debian" )